### ISSUE TITLE
temperatura da resposta

### ISSUE THREAD

**Issue by hiagocosta** [alexandremendoncaalvaro/skill-alexa-chatgpt4#2]
cara, sensacional!
estou usando o gpt 3.5turbo, haveria uma forma de reduzir a temperatura do retorno?

**Comment by alexandremendoncaalvaro** [comment]
Tem como sim! e também, entre outras coisas, o tamanho das respostas com o max_tokens (que considera a soma dos tokens tando das perguntas quanto respostas).
A temperatura é o quanto ela vai alucinar pra gerar a resposta, vai de 0 a 2. Valores mais altos, como 0.8, tornarão a saída mais aleatória, enquanto valores mais baixos, como 0.2, a tornarão mais focada e determinística. o Padrão é 1.

Exemplo com temperatura e max_tokens:
```python
def generate_gpt_response(query):
    try:
        messages.append(
            {"role": "user", "content": query},
        )
        response = client.chat.completions.create(model=MODEL, messages=messages, max_tokens=700, temperature=0.8)
        reply = response.choices[0].message.content
        messages.append({"role": "assistant", "content": reply})
        return reply
    except Exception as e:
        return f"Erro ao gerar resposta: {str(e)}"
```
